openapi: "3.0.3"
info:
  title: "MoviesSeriesShare API"
  description: "API para compartir críticas de películas y series"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /critics:
    get:
      summary: Obtener todas las críticas
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CriticsResponse'
        "404":
          description: No se encontraron críticas
    
    post:
      summary: Crear una nueva crítica
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Critics'
      responses:
        "201":
          description: "Crítica creada"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriticsResponse'
        "400":
          description: Error en la solicitud
  
  /critics/{id}:
    get:
      summary: Obtener una crítica por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriticsResponse'
        "400":
          description: ID inválido
        "404":
          description: Crítica no encontrada
        "500":
          description: Error interno del servidor
    
    put:
      summary: Actualizar una crítica existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Critics'
      responses:
        "200":
          description: "Crítica actualizada"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriticsResponse'
        "400":
          description: ID inválido o datos de entrada inválidos
        "404":
          description: Crítica no encontrada
        "500":
          description: Error interno del servidor

  /groups:
    get:
      summary: Obtener todos los grupos
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GroupResponse'
        "500":
          description: Error interno del servidor
    
    post:
      summary: Crear un nuevo grupo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupRequest'
      responses:
        "201":
          description: "Grupo creado"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupResponse'
        "400":
          description: Error en la solicitud
  
  /groups/{id}:
    get:
      summary: Obtener un grupo por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupResponse'
        "400":
          description: ID inválido
        "404":
          description: Grupo no encontrado
        "500":
          description: Error interno del servidor

    delete:
      summary: Eliminar un grupo (solo el creador puede hacerlo)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: query
          required: true
          schema:
            type: string
          description: ID del usuario que intenta eliminar el grupo
      responses:
        "200":
          description: "Grupo eliminado correctamente"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "400":
          description: ID inválido o ID de usuario no proporcionado
        "403":
          description: El usuario no es el creador del grupo
        "404":
          description: Grupo no encontrado
        "500":
          description: Error interno del servidor
  
  /groups/by-member/{memberId}:
    get:
      summary: Obtener todos los grupos donde un usuario es miembro
      parameters:
        - name: memberId
          in: path
          required: true
          schema:
            type: string
          description: ID del usuario miembro
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GroupResponse'
        "400":
          description: ID de miembro inválido
        "500":
          description: Error interno del servidor
  
  /groups/member/{memberId}/critics:
    get:
      summary: Obtener todas las opiniones de los grupos a los que pertenece un usuario
      description: Devuelve todas las críticas que se han publicado en todos los grupos de los que el usuario es miembro
      parameters:
        - name: memberId
          in: path
          required: true
          schema:
            type: string
          description: ID del usuario miembro
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CriticsResponse'
        "400":
          description: ID de miembro inválido
        "500":
          description: Error interno del servidor
  
  /groups/join/{inviteCode}:
    post:
      summary: Unirse a un grupo mediante código de invitación
      parameters:
        - name: inviteCode
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JoinGroupRequest'
      responses:
        "200":
          description: "Se unió al grupo exitosamente"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupResponse'
        "400":
          description: Código de invitación inválido
        "404":
          description: Grupo no encontrado
        "500":
          description: Error interno del servidor

  /groups/{groupId}/leave:
    delete:
      summary: Salir de un grupo (cualquier miembro, incluido el creador)
      description: |
        Permite a cualquier miembro salir del grupo. Si el que sale es el creador:
        - Si quedan otros miembros, la propiedad se transfiere al siguiente miembro
        - Si era el último miembro, el grupo se elimina automáticamente
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: query
          required: true
          schema:
            type: string
          description: ID del usuario que desea salir del grupo
      responses:
        "200":
          description: "Usuario salió del grupo exitosamente"
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      message:
                        type: string
                        description: Mensaje informativo sobre el resultado de la operación
                      group:
                        $ref: '#/components/schemas/GroupResponse'
                  - type: object
                    properties:
                      message:
                        type: string
                        description: Mensaje informando que el grupo fue eliminado (cuando el creador era el último miembro)
        "400":
          description: ID inválido, ID de usuario no proporcionado, o el usuario no es miembro del grupo
        "404":
          description: Grupo no encontrado
        "500":
          description: Error interno del servidor
  
  /groups/{groupId}/critics:
    get:
      summary: Obtener todas las críticas de un grupo específico
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CriticsResponse'
        "400":
          description: ID de grupo inválido
        "404":
          description: Grupo no encontrado
        "500":
          description: Error interno del servidor
    
    post:
      summary: Crear una nueva crítica dentro de un grupo
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Critics'
      responses:
        "201":
          description: "Crítica creada en el grupo"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriticsResponse'
        "400":
          description: Error en la solicitud o ID de grupo inválido
        "404":
          description: Grupo no encontrado
        "500":
          description: Error interno del servidor

components:
  schemas:
    Comment:
      type: object
      properties:
        text:
          type: string
          description: El texto del comentario
        username:
          type: string
          description: Nombre de usuario de quien escribió el comentario
      required:
        - text
        - username
        
    Critics:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          description: Título de la película o serie
        rating:
          type: number
          format: float
          description: Calificación (0-5)
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
          description: Lista de comentarios o críticas
        imageUrl:
          type: string
          description: URL de la imagen
        genre:
          type: string
          description: Género de la película o serie
        platform:
          type: string
          description: Plataforma donde está disponible
        year:
          type: string
          description: Año de lanzamiento
        duration:
          type: string
          description: Duración
        contentRating:
          type: string
          description: Clasificación por edades
        synopsis:
          type: string
          description: Sinopsis
        posterUrl:
          type: string
          nullable: true
          description: URL del póster
        backdropUrl:
          type: string
          nullable: true
          description: URL del backdrop
        ratingCount:
          type: integer
          description: Número de calificaciones
        averageRating:
          type: number
          format: float
          description: Calificación promedio
        groupId:
          type: string
          nullable: true
          description: ID del grupo al que pertenece esta crítica (opcional)
        username:
          type: string
          description: Nombre de usuario de quien creó la opinión
      required:
        - title
        - rating
        - comments
        - genre
        
    CriticsResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        rating:
          type: number
          format: float
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
        imageUrl:
          type: string
        genre:
          type: string
        platform:
          type: string
        year:
          type: string
        duration:
          type: string
        contentRating:
          type: string
        synopsis:
          type: string
        posterUrl:
          type: string
          nullable: true
        backdropUrl:
          type: string
          nullable: true
        ratingCount:
          type: integer
        averageRating:
          type: number
          format: float
        groupId:
          type: string
          nullable: true
          description: ID del grupo al que pertenece esta crítica (opcional)
        username:
          type: string
          description: Nombre de usuario de quien creó la opinión
      required:
        - id
        - title
        - rating
        - comments
        - genre
    
    User:
      type: object
      properties:
        id:
          type: string
          description: ID único del usuario
        name:
          type: string
          description: Nombre del usuario
        email:
          type: string
          description: Correo electrónico del usuario
      required:
        - id
        - name
        - email
    
    UserResponse:
      type: object
      properties:
        id:
          type: string
          description: ID único del usuario
        name:
          type: string
          description: Nombre del usuario
        email:
          type: string
          description: Correo electrónico del usuario
      required:
        - id
        - name
        - email
        
    GroupRequest:
      type: object
      properties:
        name:
          type: string
          description: Nombre del grupo
        description:
          type: string
          description: Descripción del grupo
        createdBy:
          type: string
          description: ID del creador del grupo
        creatorName:
          type: string
          description: Nombre del creador del grupo
        creatorEmail:
          type: string
          description: Correo electrónico del creador del grupo
      required:
        - name
        - createdBy
        - creatorName
        - creatorEmail
    
    GroupResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        createdBy:
          type: string
        createdAt:
          type: integer
          format: int64
        members:
          type: array
          items:
            $ref: '#/components/schemas/UserResponse'
          description: Lista de miembros del grupo con información completa
        memberCount:
          type: integer
        inviteCode:
          type: string
      required:
        - id
        - name
        - createdBy
        - members
        - inviteCode
    
    JoinGroupRequest:
      type: object
      properties:
        userId:
          type: string
          description: ID del usuario que se une al grupo
        userName:
          type: string
          description: Nombre del usuario que se une al grupo
        userEmail:
          type: string
          description: Correo electrónico del usuario que se une al grupo
      required:
        - userId
        - userName
        - userEmail