openapi: "3.0.3"
info:
  title: "MoviesSeriesShare API"
  description: "API para compartir críticas de películas y series"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /critics:
    get:
      summary: Obtener todas las críticas
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CriticsResponse'
        "404":
          description: No se encontraron críticas
    
    post:
      summary: Crear una nueva crítica
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Critics'
      responses:
        "201":
          description: "Crítica creada"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriticsResponse'
        "400":
          description: Error en la solicitud
  
  /critics/{id}:
    get:
      summary: Obtener una crítica por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriticsResponse'
        "400":
          description: ID inválido
        "404":
          description: Crítica no encontrada
        "500":
          description: Error interno del servidor
    
    put:
      summary: Actualizar una crítica existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Critics'
      responses:
        "200":
          description: "Crítica actualizada"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CriticsResponse'
        "400":
          description: ID inválido o datos de entrada inválidos
        "404":
          description: Crítica no encontrada
        "500":
          description: Error interno del servidor

components:
  schemas:
    Critics:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          description: Título de la película o serie
        rating:
          type: number
          format: float
          description: Calificación (0-5)
        comment:
          type: string
          description: Comentario o crítica
        imageUrl:
          type: string
          description: URL de la imagen
        genre:
          type: string
          description: Género de la película o serie
        platform:
          type: string
          description: Plataforma donde está disponible
        year:
          type: string
          description: Año de lanzamiento
        duration:
          type: string
          description: Duración
        contentRating:
          type: string
          description: Clasificación por edades
        synopsis:
          type: string
          description: Sinopsis
        posterUrl:
          type: string
          nullable: true
          description: URL del póster
        backdropUrl:
          type: string
          nullable: true
          description: URL del backdrop
        ratingCount:
          type: integer
          description: Número de calificaciones
        averageRating:
          type: number
          format: float
          description: Calificación promedio
      required:
        - title
        - rating
        - comment
        - genre
        
    CriticsResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        rating:
          type: number
          format: float
        comment:
          type: string
        imageUrl:
          type: string
        genre:
          type: string
        platform:
          type: string
        year:
          type: string
        duration:
          type: string
        contentRating:
          type: string
        synopsis:
          type: string
        posterUrl:
          type: string
          nullable: true
        backdropUrl:
          type: string
          nullable: true
        ratingCount:
          type: integer
        averageRating:
          type: number
          format: float
      required:
        - id
        - title
        - rating
        - comment
        - genre